image:
  repository: waste-detector
  tag: dev
  pullPolicy: IfNotPresent

openCostURL: "http://opencost.opencost.svc.cluster.local:9003"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi